name: Deploy Docs on Release

on:
  push:
    branches:
      - main
  release:
    types: [ published ]
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set environment variables
        run: echo "GITHUB_ACTOR=${{ github.actor }}" >> $GITHUB_ENV

      - name: Set GitHub identity
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
      
      - name: Prepare gh-pages
        run: |
          git fetch origin
          if ! git rev-parse --verify origin/gh-pages; then
            git checkout -b gh-pages
            git push -u origin gh-pages
            echo "Created new gh-pages branch."
          else
            git checkout gh-pages
            git merge main --strategy-option theirs
            git add .
            echo "Merged main to existing gh-pages branch."
          fi
          git branch
          
      - run: chmod +x scripts/unix/*

      # Install Turborepo
      - run: npm i
          
      - name: Generate docs
        run: |
          ./scripts/unix/prepare-gh-pages.sh
          npm run generate-docs
          ./scripts/unix/commit-docs-generation.sh