name: Deploy Docs on Release

on:
  push:
    branches:
      - main
  release:
    types: [ published ]
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set environment variables
        run: echo "GITHUB_ACTOR=${{ github.actor }}" >> $GITHUB_ENV

      - name: Set GitHub identity
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"

      # Install Turborepo
      - run: npm i

      # Make all scripts executable
      - run: chmod +x scripts/unix/*
          
      - name: Generate docs
        run: npm run generate-docs
      
      - name: Commit docs
        run: ./scripts/unix/commit-docs-generation.sh