name: Deploy Docs on Release

on:
  push:
    branches:
      - main
  release:
    types: [ published ]
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Commit and push changes
        run: npm run generate-full-docs:root